export const TOGGLE_MENU = "TOGGLE_MENU";
export const CREATE_TEAM = "CREATE_TEAM";

export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const TOGGLE_PERSONAL = 'TOGGLE_PERSONAL';
export const TOGGLE_ORGANIZATION = 'TOGGLE_ORGANIZATION';
